### ISSUE TITLE
question:  why not support vfs for kubernetes?

### ISSUE THREAD

**Issue by zhucan** [kubernetes/system-validators#17]
https://github.com/kubernetes/system-validators/blob/b79073534e2427cf13f6db9f41de1de7fea6a479/validators/types_unix.go#L73 skip the vfs

**Comment by zhucan** [comment]
@neolit123

**Comment by neolit123** [comment]
please open this ticket in kubernetes/kubernetes, add some more detail about your use case and tag the ticket with this command:
```
/sig node storage
```

/close

**Comment by neolit123** [comment]
if this library (system-validators) is supposed to support vfs we can update it, but it first needs a discussion with the maintainers of the kubelet and storage.

**Comment by zhucan** [comment]
> if this library (system-validators) is supposed to support vfs we can update it, but it first needs a discussion with the maintainers of the kubelet and storage.

Thanks
