### ISSUE TITLE
github.com/pkg/errors is archived

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/system-validators#33]
https://github.com/kubernetes/system-validators/blob/737f948078e6648f34337a8aaff892f1d846bf6b/go.mod#L7

https://github.com/kubernetes/kubernetes/issues/113627#issuecomment-1308742508
should we use it in this project? Or will we keep this similar with kubeadm?

**Comment by neolit123** [comment]
i remember that system validators were imported not only in kubeadm but also in k/k/test node e2e. not sure if still true.

in any case, probably best to not import it here to avoid other k8s components and third party users depending on it.
