### ISSUE TITLE
Update the kernel configuration for cgroup v2

### ISSUE THREAD

**Issue by KentaTada** [kubernetes/system-validators#36]
Kubernetes 1.25 brings cgroup v2 to GA. 
cgroup v2 needs some additional kernel configs.
For example, you need to enable `CONFIG_CGROUP_BPF` if you want to use the the device controller.
When it comes to Kubernetes, I have never investigated what config is actually needed.
But I just create an issue at first.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/system-validators/pull/12#issuecomment-607668321 by @odinuge
> CONFIG_CGROUP_BPF - Required for cgroupv2 (for controlling devices)

https://github.com/containerd/containerd/pull/3799#issuecomment-555740694 by @AkihiroSuda 
> kernel >= 4.15 with CONFIG_CGROUP_DEVICE and CONFIG_CGROUP_BPF is required.

/cc @bobbypage @mrunalp 
for cgroup v2 GA

https://github.com/kubernetes/minikube/pull/6572

**Comment by neolit123** [comment]
/remove-lifecycle rotten
@pacoxu @KentaTada do we still need such a change?

**Comment by KentaTada** [comment]
Yes. We need to investigate and prepare for the kernel configuration for cgroupv2.
If I have time, I'll investigate it.

**Comment by neolit123** [comment]
thanks, @KentaTada

**Comment by pacoxu** [comment]
The v1.31 KEP https://github.com/kubernetes/enhancements/issues/4569

- https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4569-cgroup-v1-maintenance-mode/README.md KEP-4569: Moving cgroup v1 support into maintenance mode

I opened https://github.com/kubernetes/system-validators/pull/37 for the kernel version.
- for `KernelConfig` part, I need to check the list.

**Comment by neolit123** [comment]
> Yes. We need to investigate and prepare for the kernel configuration for cgroupv2. If I have time, I'll investigate it.

@KentaTada 
should we include this in the next system-validators release too?

@pacoxu recently added:
- https://github.com/kubernetes/system-validators/pull/38
- https://github.com/kubernetes/system-validators/pull/37

**Comment by KentaTada** [comment]
> @KentaTada should we include this in the next system-validators release too?

Yes.
Although I haven't completely caught up with these commits yet, we should include the info about cgroup v2 before moving cgroup v1 support into maintenance mode.

BTW, we also need to update [the list of kernel config](https://github.com/kubernetes/system-validators/blob/1e0d9c33b4d2294743bc03b6154a9538ad64e340/validators/types_unix.go#L36-L67).
For example, CONFIG_CGROUP_FREEZER is not actually required for cgroup v2.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.8#n1006
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v6.10#n1103

**Comment by neolit123** [comment]
would you have time to send a PR or give us the info of all the required changes that we need to do?

**Comment by pacoxu** [comment]
CONFIG_CGROUP_DEVICE and CONFIG_CGROUP_BPF



> we also need to update [the list of kernel config](https://github.com/kubernetes/system-validators/blob/1e0d9c33b4d2294743bc03b6154a9538ad64e340/validators/types_unix.go#L36-L67).
> For example, CONFIG_CGROUP_FREEZER is not actually required for cgroup v2.
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.8#n1006
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v6.10#n1103

For cgroup v2, we use `cgroup.freeze` instead, which needs kernel 5.2+.

**Comment by KentaTada** [comment]
I'm sorry but  I need to support my family this week.
In addition to that, I need to chair a meeting of KubeDay and my local CNCF-related eBPF event in August.
https://sched.co/1eh9w
https://community.cncf.io/e/m4e8cg/

> For cgroup v2, we use cgroup.freeze instead, which needs kernel 5.2+.

What I wanted to say is that we need to prepare for how to detect what cgroup v2 features are available.
Unlike in v1, the kernel config alone cannot determine whether the required v2 features are enabled.
Maybe, it is possible if this validator checks for the existence of the file of cgroup.freeze.
We also need to think about BPF-based interfaces like the device controller.
In addition to that, we need to confirm what v2 features are currently needed for k8s at first.
This change should be made with caution because k8s users all over the world may recompile their kernel by the result of kubeadm.

**Comment by neolit123** [comment]
> I'm sorry but  I need to support my family this week.
In addition to that, I need to chair a meeting of KubeDay and my local CNCF-related eBPF event in August.

1.31 was just released so this is planned for 1.32. we have a whole k8s release cycle to tackle the feature detection for cgroups v2.

> What I wanted to say is that we need to prepare for how to detect what cgroup v2 features are available.
> Unlike in v1, the kernel config alone cannot determine whether the required v2 features are enabled.
> Maybe, it is possible if this validator checks for the existence of the file of cgroup.freeze.
> We also need to think about BPF-based interfaces like the device controller.

i think having the cgroups v2 validation load additional files should be fine.

> In addition to that, we need to confirm what v2 features are currently needed for k8s at first.

@pacoxu maybe we need to ask SIG node and bring them this this thread?

> This change should be made with caution because k8s users all over the world may recompile their kernel by the result of kubeadm.

completely agree.

**Comment by pacoxu** [comment]
> > What I wanted to say is that we need to prepare for how to detect what cgroup v2 features are available.
> > Unlike in v1, the kernel config alone cannot determine whether the required v2 features are enabled.
> > Maybe, it is possible if this validator checks for the existence of the file of cgroup.freeze.
> > We also need to think about BPF-based interfaces like the device controller.
> 
> i think having the cgroups v2 validation load additional files should be fine.

In https://github.com/kubernetes/kubernetes/pull/126595, we may use `cpu.stats` check instead of version check there.

**Comment by neolit123** [comment]
@KentaTada @pacoxu 
can we done this for the 1.32 release cycle?

core freeze is 7th of Nov 2024.
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.32

**Comment by pacoxu** [comment]
I would like to give it a try in this release.
