### ISSUE TITLE
OSValidator doesn't work on Windows 

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/system-validators#39]
It looks like this supports windows since there is a [windows spec](https://github.com/kubernetes/system-validators/blob/1e0d9c33b4d2294743bc03b6154a9538ad64e340/validators/types_windows.go#L28) but os validator fails:

```
Validating os...
Validating kernel...
KERNEL_VERSION: 10.0.22631
failed to get os name: exec: "uname": executable file not found in %PATH%
```

**Comment by pacoxu** [comment]
This seems to be added for a long time(5 years ago).

Do we have windows CI for this or kubeadm windows CI? @neolit123

**Comment by neolit123** [comment]
kubeadm team does not, but sig windows had/has e2e tests. currently i believe mostly capz is validating kubeadm. @jsturtevant has this been failing for a while?

this is the first report i see about this, so i wonder if uname exists in some windows servers as a stock tool? i don't think it's available by default as it's a unix-ism. long ago i was testing kubeadm on windows and don't remember this being a problem.

**Comment by pacoxu** [comment]
Probably, I should use the kubelet way https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/pkg/kubelet/winstats/version.go#L34-L76 to get the windows kernel version .

**Comment by neolit123** [comment]
not a fan of poking the registry.

kernel version is not the problem, as we already use the correct tool for that.
https://github.com/kubernetes/system-validators/blob/1e0d9c33b4d2294743bc03b6154a9538ad64e340/validators/types_windows.go#L52C20-L52C67
an alternative is to just parse `ver` or `powershell (Get-ComputerInfo).OsVersion`


the problem is the uname call, for that we can parse various other powershell outputs or just `ver`.
i will give this a try.

/unassign @pacoxu 
/assign

**Comment by neolit123** [comment]
actually what the kubelet does with the registry might be the most portable way across various flavors inc nanosever.

**Comment by neolit123** [comment]
PR attempt, PTAL:
https://github.com/kubernetes/system-validators/pull/40

**Comment by jsturtevant** [comment]
> kubeadm team does not, but sig windows had/has e2e tests. currently i believe mostly capz is validating kubeadm. @jsturtevant has this been failing for a while?

I don't see any issues in kubeadm.  I am not sure exactly where it is used in kubeadm though.

I was exploring enabled the e2e_node test suite and found it when [validation ran](https://github.com/kubernetes/kubernetes/blob/32077a1c008a59d797e4f4ae8717a0dbbe3c3db7/test/e2e_node/e2e_node_suite_test.go#L229)

> this is the first report i see about this, so i wonder if uname exists in some windows servers (and nanoserver) as a stock tool? 

No I don't think it is used in windows server anywhere.  It might be in the e2e test nano server images we use like busybox but that is installed seperately.
